name: Preprocessing Data

on: 
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Aman: install hanya paket pip valid
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Check Directory
      run: |
        ls -l

    - name: Run Preprocessing Data
      run: |
        cd preprocessing
        python automate_Ardi.py ../Predict_Student_Performance_raw/data.csv

    - name: Commit and Push Preprocessed Data
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add Predict_Student_Performance_preprocessing/*
        git commit -m "chore: update preprocessed train/test data"
        git push
      continue-on-error: true