name: Debug Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  debug-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Step 1 - Print Hello
        run: echo "Hello, World!"
          
      - name: Step 2 - Print Working Directory
        run: pwd
          
      - name: Step 3 - List Files
        run: ls -lah
